#!/bin/bash
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=crowd"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=scmgit"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=gitlab"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=kotlin"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=ldap"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=csharp"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=cssfamily"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=flex"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=go"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=web"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=javascript"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=java"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=php"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=python"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=typescript"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=xml"
curl -X POST  -u admin:admin "http://localhost:9000/api/plugins/install?key=scmsvn"